avatars.avatar_service.settings.avatars_ak_common:ringicon:
  type: avatars.avatar_service_common_base

avatars.avatar_service.settings.avatars_ak_common:ringicon:
  type: avatars.avatar_service_common_base

